version: '3.8'
services:
  mongo:
    image: mongo:3.6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

  sails-app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongodb:27017/url-tracker"
    ports:
      - "1337:1337"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
