version: '3.8'

services:
  sails-app:
    build: .
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/sailsdb
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
